# Generated by Django 3.2.4 on 2021-09-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='колмчество'),
        ),
    ]
