# Generated by Django 3.2.4 on 2021-09-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
        ('workorder', '0003_alter_workitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part')),
            ],
            options={
                'verbose_name': 'запчасти к заказ-наряду',
            },
        ),
    ]
