# Generated by Django 3.1.7 on 2021-04-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('FM', 'формируется'), ('RD', 'обработан'), ('DN', 'выполнен')], default='FM', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
