# Generated by Django 3.2.4 on 2021-09-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'производители',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=128)),
                ('in_stock', models.BooleanField(verbose_name='наличие')),
                ('quantity', models.IntegerField(verbose_name='количество на складе')),
                ('name', models.CharField(max_length=128, verbose_name='наименование')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.brand')),
            ],
            options={
                'verbose_name': 'запчасть',
                'verbose_name_plural': 'запчасти',
            },
        ),
    ]
