# Generated by Django 3.2.4 on 2021-09-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='customer_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='part',
            name='price_in',
            field=models.IntegerField(default=0),
        ),
    ]
